version: "3.8"
services:

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proposta
    ports:
      - 3306:3306
    volumes:
      - proposta_volume:/var/lib/mysql


  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-volume:/etc/prometheus/
    network_mode: bridge
    ports:
      - "9090:9090"