version: "3.8"
  services:
    bd:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proposta
    ports:
      - 3306:3306
    volumes:
      - proposta_volume:/var/lib/mysql

    app:
      build:
        context: build/libs
        dockerfile: ../../Dockerfile
        network: host
      ports:
        - 8083:8083
      depends_on:
        - bd
  volumes:
    database-data:
