version: "3.8"
services:

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proposta
    ports:
      - 3306:3306
    volumes:
      - proposta_volume:/var/lib/mysql
